const CompaniesMock = [
  {
      "__typename": "Company",
      "id": "A",
      "name": "Agilent Technologies, Inc.",
      "sector": "Healthcare",
      "country": "United States",
      "full_time_employees": 17000,
      "compensation_risk": 3,
      "audit_risk": 10,
      "board_risk": 6,
      "overall_risk": 8,
      "long_business_summary": "Agilent Technologies, Inc. provides application focused solutions to the life sciences, diagnostics, and applied chemical markets worldwide. The Life ",
      "city": "Santa Clara",
      "state": "CA",
      "website": "https://www.agilent.com"
  },
  {
      "__typename": "Company",
      "id": "AA",
      "name": "Alcoa Corporation",
      "sector": "Basic Materials",
      "country": "United States",
      "full_time_employees": 12200,
      "compensation_risk": 1,
      "audit_risk": 4,
      "board_risk": 1,
      "overall_risk": 1,
      "long_business_summary": "Alcoa Corporation, together with its subsidiaries, produces and sells bauxite, alumina, and aluminum products in the United States, Spain, Australia, ",
      "city": "Pittsburgh",
      "state": "PA",
      "website": "https://www.alcoa.com"
  },
  {
      "__typename": "Company",
      "id": "AAPL",
      "name": "Apple Inc.",
      "sector": "Technology",
      "country": "United States",
      "full_time_employees": 154000,
      "compensation_risk": 10,
      "audit_risk": 2,
      "board_risk": 1,
      "overall_risk": 3,
      "long_business_summary": "Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. It also sells various re",
      "city": "Cupertino",
      "state": "CA",
      "website": "https://www.apple.com"
  },
  {
      "__typename": "Company",
      "id": "ABBV",
      "name": "AbbVie Inc.",
      "sector": "Healthcare",
      "country": "United States",
      "full_time_employees": 50000,
      "compensation_risk": 3,
      "audit_risk": 10,
      "board_risk": 5,
      "overall_risk": 8,
      "long_business_summary": "AbbVie Inc. discovers, develops, manufactures, and sells pharmaceuticals in the worldwide. The company offers HUMIRA, a therapy administered as an inj",
      "city": "North Chicago",
      "state": "IL",
      "website": "https://www.abbvie.com"
  },
  {
      "__typename": "Company",
      "id": "ABM",
      "name": "ABM Industries Incorporated",
      "sector": "Industrials",
      "country": "United States",
      "full_time_employees": 100000,
      "compensation_risk": 2,
      "audit_risk": 4,
      "board_risk": 3,
      "overall_risk": 3,
      "long_business_summary": "ABM Industries Incorporated provides integrated facility solutions in the United States and internationally. The company operates through Business & I",
      "city": "New York",
      "state": "NY",
      "website": "https://www.abm.com"
  },
  {
      "__typename": "Company",
      "id": "ABR",
      "name": "Arbor Realty Trust",
      "sector": "Real Estate",
      "country": "United States",
      "full_time_employees": 579,
      "compensation_risk": 8,
      "audit_risk": 3,
      "board_risk": 9,
      "overall_risk": 7,
      "long_business_summary": "Arbor Realty Trust, Inc. invests in a diversified portfolio of structured finance assets in the multifamily, single-family rental, and commercial real",
      "city": "Uniondale",
      "state": "NY",
      "website": "https://arbor.com"
  },
  {
      "__typename": "Company",
      "id": "ABT",
      "name": "Abbott Laboratories",
      "sector": "Healthcare",
      "country": "United States",
      "full_time_employees": 113000,
      "compensation_risk": 5,
      "audit_risk": 7,
      "board_risk": 6,
      "overall_risk": 4,
      "long_business_summary": "Abbott Laboratories, together with its subsidiaries, discovers, develops, manufactures, and sells health care products worldwide. It operates in four ",
      "city": "North Chicago",
      "state": "IL",
      "website": "https://www.abbott.com"
  },
  {
      "__typename": "Company",
      "id": "AC",
      "name": "Associated Capital Group, Inc.",
      "sector": "Financial Services",
      "country": "United States",
      "full_time_employees": 25,
      "compensation_risk": 8,
      "audit_risk": 10,
      "board_risk": 10,
      "overall_risk": 10,
      "long_business_summary": "Associated Capital Group, Inc. provides investment advisory services in the United States. The company offers alternative investment management and as",
      "city": "Greenwich",
      "state": "CT",
      "website": "https://www.associated-capital-group.com"
  },
  {
      "__typename": "Company",
      "id": "ADBE",
      "name": "Adobe Corp.",
      "sector": "Technology",
      "country": "United States",
      "full_time_employees": 25988,
      "compensation_risk": 8,
      "audit_risk": 4,
      "board_risk": 6,
      "overall_risk": 4,
      "long_business_summary": "Adobe Inc. operates as a diversified software company worldwide. It operates through three segments: Digital Media, Digital Experience, and Publishing",
      "city": "San Jose",
      "state": "CA",
      "website": "https://www.adobe.com"
  },
  {
      "__typename": "Company",
      "id": "ADT",
      "name": "ADT Inc.",
      "sector": "Industrials",
      "country": "United States",
      "full_time_employees": 25000,
      "compensation_risk": 6,
      "audit_risk": 4,
      "board_risk": 10,
      "overall_risk": 9,
      "long_business_summary": "ADT Inc. provides security, automation, and smart home solutions to consumer and business customers in the United States. It provides a range of fire ",
      "city": "Boca Raton",
      "state": "FL",
      "website": "https://www.adt.com"
  },
  {
      "__typename": "Company",
      "id": "AEE",
      "name": "Ameren Corporation",
      "sector": "Utilities",
      "country": "United States",
      "full_time_employees": 9116,
      "compensation_risk": 3,
      "audit_risk": 7,
      "board_risk": 6,
      "overall_risk": 6,
      "long_business_summary": "Ameren Corporation, together with its subsidiaries, operates as a public utility holding company in the United States. It operates through four segmen",
      "city": "Saint Louis",
      "state": "MO",
      "website": "https://www.ameren.com"
  },
  {
      "__typename": "Company",
      "id": "AGS",
      "name": "PlayAGS, Inc.",
      "sector": "Consumer Cyclical",
      "country": "United States",
      "full_time_employees": 780,
      "compensation_risk": 10,
      "audit_risk": 8,
      "board_risk": 8,
      "overall_risk": 9,
      "long_business_summary": "PlayAGS, Inc. designs and supplies gaming products and services for the gaming industry in the United States and internationally. It operates through ",
      "city": "Las Vegas",
      "state": "NV",
      "website": "https://www.playags.com"
  },
  {
      "__typename": "Company",
      "id": "AGX",
      "name": "Argan, Inc.",
      "sector": "Industrials",
      "country": "United States",
      "full_time_employees": 1358,
      "compensation_risk": 3,
      "audit_risk": 6,
      "board_risk": 3,
      "overall_risk": 3,
      "long_business_summary": "Argan, Inc., through its subsidiaries, provides engineering, procurement, construction, commissioning, operations management, maintenance, project dev",
      "city": "Rockville",
      "state": "MD",
      "website": "https://www.arganinc.com"
  },
  {
      "__typename": "Company",
      "id": "AMP",
      "name": "AMERIPRISE FINANCIAL SERVICES, INC.",
      "sector": "Financial Services",
      "country": "United States",
      "full_time_employees": 12000,
      "compensation_risk": 5,
      "audit_risk": 1,
      "board_risk": 8,
      "overall_risk": 5,
      "long_business_summary": "Ameriprise Financial, Inc., through its subsidiaries, provides various financial products and services to individual and institutional clients in the ",
      "city": "Minneapolis",
      "state": "MN",
      "website": "https://www.ameriprise.com"
  },
  {
      "__typename": "Company",
      "id": "AMZN",
      "name": "Amazon",
      "sector": "Consumer Cyclical",
      "country": "United States",
      "full_time_employees": 1523000,
      "compensation_risk": 10,
      "audit_risk": 3,
      "board_risk": 8,
      "overall_risk": 10,
      "long_business_summary": "Amazon.com, Inc. engages in the retail sale of consumer products and subscriptions in North America and internationally. The company operates through ",
      "city": "Seattle",
      "state": "WA",
      "website": "https://www.amazon.com"
  },
  {
      "__typename": "Company",
      "id": "APO",
      "name": "Apollo Global Management, Inc",
      "sector": "Financial Services",
      "country": "United States",
      "full_time_employees": 2153,
      "compensation_risk": 8,
      "audit_risk": 2,
      "board_risk": 5,
      "overall_risk": 5,
      "long_business_summary": "Apollo Global Management, Inc. is a private equity firm specializing in investments in credit, private equity and real estate markets. The firm's priv",
      "city": "New York",
      "state": "NY",
      "website": "https://www.apollo.com"
  },
  {
      "__typename": "Company",
      "id": "ATEN",
      "name": "A10 Networks, Inc.",
      "sector": "Technology",
      "country": "United States",
      "full_time_employees": 590,
      "compensation_risk": 7,
      "audit_risk": 4,
      "board_risk": 6,
      "overall_risk": 6,
      "long_business_summary": "A10 Networks, Inc. provides networking solutions in the Americas, Japan, other Asia Pacific, and EMEA countries. The company offers Thunder Applicatio",
      "city": "San Jose",
      "state": "CA",
      "website": "https://www.a10networks.com"
  },
  {
      "__typename": "Company",
      "id": "ATVI",
      "name": "Acorn International, Inc.",
      "sector": "Communication Services",
      "country": "United States",
      "full_time_employees": 9800,
      "compensation_risk": 10,
      "audit_risk": 10,
      "board_risk": 8,
      "overall_risk": 10,
      "long_business_summary": "Activision Blizzard, Inc., together with its subsidiaries, develops and publishes interactive entertainment content and services in the Americas, Euro",
      "city": "Santa Monica",
      "state": "CA",
      "website": "https://www.activisionblizzard.com"
  },
  {
      "__typename": "Company",
      "id": "BKU",
      "name": "BankUnited, Inc.",
      "sector": "Financial Services",
      "country": "United States",
      "full_time_employees": 1465,
      "compensation_risk": 4,
      "audit_risk": 4,
      "board_risk": 2,
      "overall_risk": 2,
      "long_business_summary": "BankUnited, Inc. operates as the bank holding company for BankUnited, a national banking association that provides a range of banking services in the ",
      "city": "Miami Lakes",
      "state": "FL",
      "website": "https://www.bankunited.com"
  },
  {
      "__typename": "Company",
      "id": "BLD",
      "name": "TopBuild Corp.",
      "sector": "Industrials",
      "country": "United States",
      "full_time_employees": 13006,
      "compensation_risk": 1,
      "audit_risk": 5,
      "board_risk": 4,
      "overall_risk": 2,
      "long_business_summary": "TopBuild Corp., together with its subsidiaries, engages in the installation and distribution of insulation and other building products to the construc",
      "city": "Daytona Beach",
      "state": "FL",
      "website": "https://www.topbuild.com"
  },
  {
      "__typename": "Company",
      "id": "BOX",
      "name": "Box, Inc.",
      "sector": "Technology",
      "country": "United States",
      "full_time_employees": 2172,
      "compensation_risk": 6,
      "audit_risk": 2,
      "board_risk": 7,
      "overall_risk": 4,
      "long_business_summary": "Box, Inc. provides a cloud content management platform that enables organizations of various sizes to manage and share their content from anywhere on ",
      "city": "Redwood City",
      "state": "CA",
      "website": "https://www.box.com"
  },
  {
      "__typename": "Company",
      "id": "BV",
      "name": "BrightView Holdings, Inc.",
      "sector": "Industrials",
      "country": "United States",
      "full_time_employees": 19800,
      "compensation_risk": 5,
      "audit_risk": 5,
      "board_risk": 5,
      "overall_risk": 4,
      "long_business_summary": "BrightView Holdings, Inc., through its subsidiaries, provides commercial landscaping services in the United States. It operates through two segments, ",
      "city": "Blue Bell",
      "state": "PA",
      "website": "https://www.brightview.com"
  },
  {
      "__typename": "Company",
      "id": "BW",
      "name": "Babcock",
      "sector": "Industrials",
      "country": "United States",
      "full_time_employees": 1750,
      "compensation_risk": 5,
      "audit_risk": 5,
      "board_risk": 6,
      "overall_risk": 6,
      "long_business_summary": "Babcock & Wilcox Enterprises, Inc., together with its subsidiaries, provides energy and emissions control solutions to a range of industrial, electric",
      "city": "Akron",
      "state": "OH",
      "website": "https://www.babcock.com"
  },
  {
      "__typename": "Company",
      "id": "C",
      "name": "Citigroup Inc.",
      "sector": "Financial Services",
      "country": "United States",
      "full_time_employees": 231000,
      "compensation_risk": 8,
      "audit_risk": 10,
      "board_risk": 2,
      "overall_risk": 5,
      "long_business_summary": "Citigroup Inc., a diversified financial services holding company, provides various financial products and services to consumers, corporations, governm",
      "city": "New York",
      "state": "NY",
      "website": "https://www.citigroup.com"
  },
  {
      "__typename": "Company",
      "id": "CADE",
      "name": "Cadence Bancorporation",
      "sector": "Financial Services",
      "country": "United States",
      "full_time_employees": 6659,
      "compensation_risk": 10,
      "audit_risk": 1,
      "board_risk": 3,
      "overall_risk": 8,
      "long_business_summary": "Cadence Bank provides commercial banking and financial services in the United States. Its products and services include consumer banking, consumer loa",
      "city": "Tupelo",
      "state": "MS",
      "website": "https://cadencebank.com"
  },
  {
      "__typename": "Company",
      "id": "CAT",
      "name": "Caterpillar, Inc.",
      "sector": "Industrials",
      "country": "United States",
      "full_time_employees": 107700,
      "compensation_risk": 6,
      "audit_risk": 7,
      "board_risk": 5,
      "overall_risk": 6,
      "long_business_summary": "Caterpillar Inc. manufactures and sells construction and mining equipment, diesel and natural gas engines, and industrial gas turbines worldwide. Its ",
      "city": "Deerfield",
      "state": "IL",
      "website": "https://www.caterpillar.com"
  },
  {
      "__typename": "Company",
      "id": "CCL",
      "name": "Carnival Corporation",
      "sector": "Consumer Cyclical",
      "country": "United States",
      "full_time_employees": 40000,
      "compensation_risk": 10,
      "audit_risk": 4,
      "board_risk": 10,
      "overall_risk": 10,
      "long_business_summary": "Carnival Corporation & plc operates as a leisure travel company. Its ships visit approximately 700 ports under the Carnival Cruise Line, Princess Crui",
      "city": "Miami",
      "state": "FL",
      "website": "https://www.carnivalcorp.com"
  },
  {
      "__typename": "Company",
      "id": "CCS",
      "name": "Century Communities, Inc.",
      "sector": "Consumer Cyclical",
      "country": "United States",
      "full_time_employees": 1600,
      "compensation_risk": 2,
      "audit_risk": 6,
      "board_risk": 5,
      "overall_risk": 3,
      "long_business_summary": "Century Communities, Inc., together with its subsidiaries, engages in the design, development, construction, marketing, and sale of single-family atta",
      "city": "Greenwood Village",
      "state": "CO",
      "website": "https://www.centurycommunities.com"
  },
  {
      "__typename": "Company",
      "id": "CHGG",
      "name": "Chegg, Inc.",
      "sector": "Consumer Defensive",
      "country": "United States",
      "full_time_employees": 2464,
      "compensation_risk": 6,
      "audit_risk": 9,
      "board_risk": 1,
      "overall_risk": 6,
      "long_business_summary": "Chegg, Inc. operates direct-to-student learning platform that supports students starting with their academic journey and extending into their careers ",
      "city": "Santa Clara",
      "state": "CA",
      "website": "https://www.chegg.com"
  },
  {
      "__typename": "Company",
      "id": "CIA",
      "name": "Citizens, Inc.",
      "sector": "Financial Services",
      "country": "United States",
      "full_time_employees": 215,
      "compensation_risk": 9,
      "audit_risk": 1,
      "board_risk": 6,
      "overall_risk": 5,
      "long_business_summary": "Citizens, Inc., through its subsidiaries, provides life insurance products in the United States and internationally. It operates in two segments, Life",
      "city": "Austin",
      "state": "TX",
      "website": "https://www.citizensinc.com"
  },
  {
      "__typename": "Company",
      "id": "CL",
      "name": "Colgate-Palmolive Company",
      "sector": "Consumer Defensive",
      "country": "United States",
      "full_time_employees": 33800,
      "compensation_risk": 2,
      "audit_risk": 4,
      "board_risk": 3,
      "overall_risk": 1,
      "long_business_summary": "Colgate-Palmolive Company, together with its subsidiaries, manufactures and sells consumer products worldwide. The company operates through two segmen",
      "city": "New York",
      "state": "NY",
      "website": "https://www.colgatepalmolive.com"
  },
  {
      "__typename": "Company",
      "id": "CMP",
      "name": "Compass Minerals International, Inc.",
      "sector": "Basic Materials",
      "country": "United States",
      "full_time_employees": 2000,
      "compensation_risk": 3,
      "audit_risk": 10,
      "board_risk": 1,
      "overall_risk": 4,
      "long_business_summary": "Compass Minerals International, Inc., produces and sells essential minerals primarily in the United States, Canada, Brazil, the United Kingdom, and in",
      "city": "Overland Park",
      "state": "KS",
      "website": "https://www.compassminerals.com"
  },
  {
      "__typename": "Company",
      "id": "COLD",
      "name": "Americold Realty Trust",
      "sector": "Real Estate",
      "country": "United States",
      "full_time_employees": 16275,
      "compensation_risk": 2,
      "audit_risk": 2,
      "board_risk": 3,
      "overall_risk": 3,
      "long_business_summary": "Americold is the world's largest publicly traded REIT focused on the ownership, operation, acquisition and development of temperature-controlled wareh",
      "city": "Atlanta",
      "state": "GA",
      "website": "https://www.americold.com"
  },
  {
      "__typename": "Company",
      "id": "CVX",
      "name": "Chevron Corporation",
      "sector": "Energy",
      "country": "United States",
      "full_time_employees": 42595,
      "compensation_risk": 9,
      "audit_risk": 4,
      "board_risk": 6,
      "overall_risk": 7,
      "long_business_summary": "Chevron Corporation, through its subsidiaries, engages in integrated energy and chemicals operations worldwide. The company operates in two segments, ",
      "city": "San Ramon",
      "state": "CA",
      "website": "https://www.chevron.com"
  },
  {
      "__typename": "Company",
      "id": "CWT",
      "name": "California Water  Service Group Holding",
      "sector": "Utilities",
      "country": "United States",
      "full_time_employees": 1182,
      "compensation_risk": 4,
      "audit_risk": 4,
      "board_risk": 3,
      "overall_risk": 2,
      "long_business_summary": "California Water Service Group, through its subsidiaries, provides water utility and other related services in California, Washington, New Mexico, Haw",
      "city": "San Jose",
      "state": "CA",
      "website": "https://www.calwatergroup.com"
  },
  {
      "__typename": "Company",
      "id": "DELL",
      "name": "Dell Technologies Inc.",
      "sector": "Technology",
      "country": "United States",
      "full_time_employees": 133000,
      "compensation_risk": 3,
      "audit_risk": 5,
      "board_risk": 10,
      "overall_risk": 10,
      "long_business_summary": "Dell Technologies Inc. designs, develops, manufactures, markets, sells, and supports information technology (IT) solutions, products, and services wor",
      "city": "Round Rock",
      "state": "TX",
      "website": "https://www.delltechnologies.com"
  },
  {
      "__typename": "Company",
      "id": "DIS",
      "name": "Walt Disney Company (The)",
      "sector": "Communication Services",
      "country": "United States",
      "full_time_employees": 152000,
      "compensation_risk": 4,
      "audit_risk": 8,
      "board_risk": 1,
      "overall_risk": 2,
      "long_business_summary": "The Walt Disney Company, together with its subsidiaries, operates as an entertainment company worldwide. It operates through two segments, Disney Medi",
      "city": "Burbank",
      "state": "CA",
      "website": "https://www.thewaltdisneycompany.com"
  },
  {
      "__typename": "Company",
      "id": "DK",
      "name": "Delek US Holdings, Inc.",
      "sector": "Energy",
      "country": "United States",
      "full_time_employees": 3312,
      "compensation_risk": 2,
      "audit_risk": 2,
      "board_risk": 3,
      "overall_risk": 2,
      "long_business_summary": "Delek US Holdings, Inc. engages in the integrated downstream energy business in the United States. The company operates through three segments: Refini",
      "city": "Brentwood",
      "state": "TN",
      "website": "https://www.delekus.com"
  },
  {
      "__typename": "Company",
      "id": "DOV",
      "name": "Dover Corporation",
      "sector": "Industrials",
      "country": "United States",
      "full_time_employees": 25000,
      "compensation_risk": 2,
      "audit_risk": 6,
      "board_risk": 1,
      "overall_risk": 1,
      "long_business_summary": "Dover Corporation provides equipment and components, consumable supplies, aftermarket parts, software and digital solutions, and support services worl",
      "city": "Downers Grove",
      "state": "IL",
      "website": "https://www.dovercorporation.com"
  },
  {
      "__typename": "Company",
      "id": "DPZ",
      "name": "Domino&#39;s Pizza Inc",
      "sector": "Consumer Cyclical",
      "country": "United States",
      "full_time_employees": 7400,
      "compensation_risk": 8,
      "audit_risk": 6,
      "board_risk": 5,
      "overall_risk": 9,
      "long_business_summary": "Domino's Pizza, Inc., through its subsidiaries, operates as a pizza company in the United States and internationally. It operates through three segmen",
      "city": "Ann Arbor",
      "state": "MI",
      "website": "https://www.dominos.com"
  },
  {
      "__typename": "Company",
      "id": "DRQ",
      "name": "Dril-Quip, Inc.",
      "sector": "Energy",
      "country": "United States",
      "full_time_employees": 1342,
      "compensation_risk": 6,
      "audit_risk": 1,
      "board_risk": 5,
      "overall_risk": 4,
      "long_business_summary": "Dril-Quip, Inc., together with its subsidiaries, designs, manufactures, sells, and services engineered drilling and production equipment for use in de",
      "city": "Houston",
      "state": "TX",
      "website": "https://www.dril-quip.com"
  },
  {
      "__typename": "Company",
      "id": "EFX",
      "name": "Equifax, Inc.",
      "sector": "Industrials",
      "country": "United States",
      "full_time_employees": 13000,
      "compensation_risk": 3,
      "audit_risk": 3,
      "board_risk": 3,
      "overall_risk": 4,
      "long_business_summary": "Equifax Inc. provides information solutions and human resources business process automation outsourcing services for businesses, governments, and cons",
      "city": "Atlanta",
      "state": "GA",
      "website": "https://www.equifax.com"
  },
  {
      "__typename": "Company",
      "id": "ELY",
      "name": "Callaway Golf Company",
      "sector": "Consumer Cyclical",
      "country": "United States",
      "full_time_employees": 24800,
      "compensation_risk": 1,
      "audit_risk": 1,
      "board_risk": 1,
      "overall_risk": 1,
      "long_business_summary": "Callaway Golf Company, together with its subsidiaries, designs, manufactures, and sells golf equipment, golf and lifestyle apparel, and other accessor",
      "city": "Carlsbad",
      "state": "CA",
      "website": "https://www.callawaygolf.com"
  },
  {
      "__typename": "Company",
      "id": "ESS",
      "name": "Essex Property Trust, Inc.",
      "sector": "Real Estate",
      "country": "United States",
      "full_time_employees": 1739,
      "compensation_risk": 2,
      "audit_risk": 2,
      "board_risk": 7,
      "overall_risk": 5,
      "long_business_summary": "Essex Property Trust, Inc., an S&P 500 company, is a fully integrated real estate investment trust (REIT) that acquires, develops, redevelops, and man",
      "city": "San Mateo",
      "state": "CA",
      "website": "https://www.essexapartmenthomes.com"
  },
  {
      "__typename": "Company",
      "id": "ESTE",
      "name": "Earthstone Energy, Inc.",
      "sector": "Energy",
      "country": "United States",
      "full_time_employees": 81,
      "compensation_risk": 8,
      "audit_risk": 6,
      "board_risk": 9,
      "overall_risk": 8,
      "long_business_summary": "Earthstone Energy, Inc., an independent oil and gas company, engages in the acquisition, exploration, development, and production of oil and natural g",
      "city": "The Woodlands",
      "state": "TX",
      "website": "https://www.earthstoneenergy.com"
  },
  {
      "__typename": "Company",
      "id": "EVR",
      "name": "Evercore Inc.",
      "sector": "Financial Services",
      "country": "United States",
      "full_time_employees": 2135,
      "compensation_risk": 5,
      "audit_risk": 4,
      "board_risk": 3,
      "overall_risk": 4,
      "long_business_summary": "Evercore Inc., together with its subsidiaries, operates as an independent investment banking advisory firm in the United States, Europe, Latin America",
      "city": "New York",
      "state": "NY",
      "website": "https://www.evercore.com"
  },
  {
      "__typename": "Company",
      "id": "EVRI",
      "name": "Everi Holdings Inc.",
      "sector": "Consumer Cyclical",
      "country": "United States",
      "full_time_employees": 1550,
      "compensation_risk": 4,
      "audit_risk": 2,
      "board_risk": 4,
      "overall_risk": 5,
      "long_business_summary": "Everi Holdings Inc. provides entertainment and technology solutions for the casino and digital gaming industries in the United States, Canada, the Uni",
      "city": "Las Vegas",
      "state": "NV",
      "website": "https://www.everi.com"
  },
  {
      "__typename": "Company",
      "id": "EXC",
      "name": "Exelon Corporation",
      "sector": "Utilities",
      "country": "United States",
      "full_time_employees": 31518,
      "compensation_risk": 1,
      "audit_risk": 10,
      "board_risk": 2,
      "overall_risk": 3,
      "long_business_summary": "Exelon Corporation, a utility services holding company, engages in the energy generation, delivery, and marketing businesses in the United States and ",
      "city": "Chicago",
      "state": "IL",
      "website": "https://www.exeloncorp.com"
  },
  {
      "__typename": "Company",
      "id": "F",
      "name": "Ford Motor Company",
      "sector": "Consumer Cyclical",
      "country": "United States",
      "full_time_employees": 183000,
      "compensation_risk": 7,
      "audit_risk": 8,
      "board_risk": 9,
      "overall_risk": 10,
      "long_business_summary": "Ford Motor Company designs, manufactures, markets, and services a range of Ford trucks, cars, sport utility vehicles, electrified vehicles, and Lincol",
      "city": "Dearborn",
      "state": "MI",
      "website": "https://www.ford.com"
  },
  {
      "__typename": "Company",
      "id": "FBP",
      "name": "First BanCorp.",
      "sector": "Financial Services",
      "country": "United States",
      "full_time_employees": 3075,
      "compensation_risk": 3,
      "audit_risk": 1,
      "board_risk": 3,
      "overall_risk": 2,
      "long_business_summary": "First BanCorp. operates as a bank holding company for FirstBank Puerto Rico that provides various financial services for retail, commercial, and insti",
      "city": "San Juan",
      "state": "PR",
      "website": "https://www.1firstbank.com"
  },
  {
      "__typename": "Company",
      "id": "FCPT",
      "name": "Four Corners Property Trust, Inc.",
      "sector": "Real Estate",
      "country": "United States",
      "full_time_employees": 461,
      "compensation_risk": 1,
      "audit_risk": 5,
      "board_risk": 2,
      "overall_risk": 1,
      "long_business_summary": "FCPT, headquartered in Mill Valley, CA, is a real estate investment trust primarily engaged in the acquisition and leasing of restaurant properties. T",
      "city": "Mill Valley",
      "state": "CA",
      "website": "https://www.fcpt.com"
  },
  {
      "__typename": "Company",
      "id": "FDX",
      "name": "FedEx Corporation",
      "sector": "Industrials",
      "country": "United States",
      "full_time_employees": 345000,
      "compensation_risk": 8,
      "audit_risk": 1,
      "board_risk": 9,
      "overall_risk": 6,
      "long_business_summary": "FedEx Corporation provides transportation, e-commerce, and business services in the United States and internationally. The company's FedEx Express seg",
      "city": "Memphis",
      "state": "TN",
      "website": "https://www.fedex.com"
  },
  {
      "__typename": "Company",
      "id": "FICO",
      "name": "Fair Isaac Corporation",
      "sector": "Technology",
      "country": "United States",
      "full_time_employees": 3367,
      "compensation_risk": 1,
      "audit_risk": 4,
      "board_risk": 1,
      "overall_risk": 1,
      "long_business_summary": "Fair Isaac Corporation develops analytic, software, and data management products and services that enable businesses to automate, enhance, and connect",
      "city": "Bozeman",
      "state": "MT",
      "website": "https://www.fico.com"
  },
  {
      "__typename": "Company",
      "id": "FLR",
      "name": "Fluor Corporation",
      "sector": "Industrials",
      "country": "United States",
      "full_time_employees": 40582,
      "compensation_risk": 2,
      "audit_risk": 10,
      "board_risk": 4,
      "overall_risk": 3,
      "long_business_summary": "Fluor Corporation provides engineering, procurement, and construction (EPC); fabrication and modularization; operation and maintenance; asset integrit",
      "city": "Irving",
      "state": "TX",
      "website": "https://www.fluor.com"
  },
  {
      "__typename": "Company",
      "id": "FMC",
      "name": "FMC Corporation",
      "sector": "Basic Materials",
      "country": "United States",
      "full_time_employees": 6400,
      "compensation_risk": 3,
      "audit_risk": 1,
      "board_risk": 9,
      "overall_risk": 6,
      "long_business_summary": "FMC Corporation, an agricultural sciences company, provides crop protection, plant health, and professional pest and turf management products. It deve",
      "city": "Philadelphia",
      "state": "PA",
      "website": "https://www.fmc.com"
  },
  {
      "__typename": "Company",
      "id": "FTNT",
      "name": "Fortinet",
      "sector": "Technology",
      "country": "United States",
      "full_time_employees": 11508,
      "compensation_risk": 8,
      "audit_risk": 6,
      "board_risk": 8,
      "overall_risk": 8,
      "long_business_summary": "Fortinet, Inc. provides broad, integrated, and automated cybersecurity solutions in the Americas, Europe, the Middle East, Africa, and the Asia Pacifi",
      "city": "Sunnyvale",
      "state": "CA",
      "website": "https://www.fortinet.com"
  },
  {
      "__typename": "Company",
      "id": "FTV",
      "name": "Fortive Corporation",
      "sector": "Technology",
      "country": "United States",
      "full_time_employees": 18000,
      "compensation_risk": 8,
      "audit_risk": 1,
      "board_risk": 2,
      "overall_risk": 4,
      "long_business_summary": "Fortive Corporation designs, develops, manufactures, markets, and services professional and engineered products, software, and services worldwide. Its",
      "city": "Everett",
      "state": "WA",
      "website": "https://www.fortive.com"
  },
  {
      "__typename": "Company",
      "id": "FUL",
      "name": "H. B. Fuller Company",
      "sector": "Basic Materials",
      "country": "United States",
      "full_time_employees": 6500,
      "compensation_risk": 4,
      "audit_risk": 6,
      "board_risk": 2,
      "overall_risk": 3,
      "long_business_summary": "H.B. Fuller Company, together with its subsidiaries, formulates, manufactures, and markets adhesives, sealants, coatings, polymers, tapes, encapsulant",
      "city": "Saint Paul",
      "state": "MN",
      "website": "https://www.hbfuller.com"
  },
  {
      "__typename": "Company",
      "id": "FUN",
      "name": "Cedar Fair, L.P.",
      "sector": "Consumer Cyclical",
      "country": "United States",
      "full_time_employees": 4000,
      "compensation_risk": 8,
      "audit_risk": 6,
      "board_risk": 1,
      "overall_risk": 5,
      "long_business_summary": "Cedar Fair, L.P. owns and operates amusement and water parks, and complementary resort facilities in the United States and Canada. Its amusement parks",
      "city": "Sandusky",
      "state": "OH",
      "website": "https://www.cedarfair.com"
  },
  {
      "__typename": "Company",
      "id": "GDDY",
      "name": "GoDaddy Inc.",
      "sector": "Technology",
      "country": "United States",
      "full_time_employees": 6611,
      "compensation_risk": 5,
      "audit_risk": 9,
      "board_risk": 7,
      "overall_risk": 6,
      "long_business_summary": "GoDaddy Inc. engages in the design and development of cloud-based technology products in the United States and internationally. The company provides d",
      "city": "Tempe",
      "state": "AZ",
      "website": "https://www.godaddy.com"
  },
  {
      "__typename": "Company",
      "id": "GM",
      "name": "General Motors Company",
      "sector": "Consumer Cyclical",
      "country": "United States",
      "full_time_employees": 157000,
      "compensation_risk": 4,
      "audit_risk": 8,
      "board_risk": 3,
      "overall_risk": 4,
      "long_business_summary": "General Motors Company designs, builds, and sells trucks, crossovers, cars, and automobile parts and accessories in North America, the Asia Pacific, t",
      "city": "Detroit",
      "state": "MI",
      "website": "https://www.gm.com"
  },
  {
      "__typename": "Company",
      "id": "GMS",
      "name": "GMS Inc.",
      "sector": "Industrials",
      "country": "United States",
      "full_time_employees": 5475,
      "compensation_risk": 3,
      "audit_risk": 1,
      "board_risk": 3,
      "overall_risk": 2,
      "long_business_summary": "GMS Inc. distributes wallboard, ceilings, steel framing and complementary construction products in the United States and Canada. The company offers ce",
      "city": "Tucker",
      "state": "GA",
      "website": "https://www.gms.com"
  },
  {
      "__typename": "Company",
      "id": "GNE",
      "name": "Genie Energy Ltd.",
      "sector": "Utilities",
      "country": "United States",
      "full_time_employees": 186,
      "compensation_risk": 9,
      "audit_risk": 10,
      "board_risk": 8,
      "overall_risk": 10,
      "long_business_summary": "Genie Energy Ltd., through its subsidiaries, supplies electricity and natural gas to residential and small business customers in the United States, Fi",
      "city": "Newark",
      "state": "NJ",
      "website": "https://www.genie.com"
  },
  {
      "__typename": "Company",
      "id": "GOLF",
      "name": "Acushnet Holdings Corp.",
      "sector": "Consumer Cyclical",
      "country": "United States",
      "full_time_employees": 6500,
      "compensation_risk": 4,
      "audit_risk": 6,
      "board_risk": 9,
      "overall_risk": 6,
      "long_business_summary": "Acushnet Holdings Corp. designs, develops, manufactures, and distributes golf products in the United States, Europe, the Middle East, Africa, Japan, K",
      "city": "Fairhaven",
      "state": "MA",
      "website": "https://www.acushnetholdingscorp.com"
  },
  {
      "__typename": "Company",
      "id": "GTN",
      "name": "Gray Television, Inc.",
      "sector": "Communication Services",
      "country": "United States",
      "full_time_employees": 8608,
      "compensation_risk": 7,
      "audit_risk": 10,
      "board_risk": 5,
      "overall_risk": 8,
      "long_business_summary": "Gray Television, Inc., a television broadcasting company, owns and/or operates television stations and digital assets in the United States. It also br",
      "city": "Atlanta",
      "state": "GA",
      "website": "https://www.gray.tv"
  },
  {
      "__typename": "Company",
      "id": "HBI",
      "name": "Hanesbrands Inc.",
      "sector": "Consumer Cyclical",
      "country": "United States",
      "full_time_employees": 59000,
      "compensation_risk": 2,
      "audit_risk": 10,
      "board_risk": 2,
      "overall_risk": 4,
      "long_business_summary": "Hanesbrands Inc., a consumer goods company, designs, manufactures, sources, and sells a range of basic apparel for men, women, and children. The compa",
      "city": "Winston-Salem",
      "state": "NC",
      "website": "https://www.hanes.com"
  },
  {
      "__typename": "Company",
      "id": "HCA",
      "name": "HCA Healthcare, Inc.",
      "sector": "Healthcare",
      "country": "United States",
      "full_time_employees": 204000,
      "compensation_risk": 5,
      "audit_risk": 2,
      "board_risk": 6,
      "overall_risk": 2,
      "long_business_summary": "HCA Healthcare, Inc., through its subsidiaries, provides health care services company in the United States. The company operates general and acute car",
      "city": "Nashville",
      "state": "TN",
      "website": "https://www.hcahealthcare.com"
  },
  {
      "__typename": "Company",
      "id": "HD",
      "name": "Home Depot, Inc. (The)",
      "sector": "Consumer Cyclical",
      "country": "United States",
      "full_time_employees": 500000,
      "compensation_risk": 5,
      "audit_risk": 3,
      "board_risk": 7,
      "overall_risk": 2,
      "long_business_summary": "The Home Depot, Inc. operates as a home improvement retailer. It operates The Home Depot stores that sell various building materials, home improvement",
      "city": "Atlanta",
      "state": "GA",
      "website": "https://www.homedepot.com"
  },
  {
      "__typename": "Company",
      "id": "HE",
      "name": "Hawaiian Electric Industries, Inc.",
      "sector": "Utilities",
      "country": "United States",
      "full_time_employees": 3597,
      "compensation_risk": 3,
      "audit_risk": 1,
      "board_risk": 1,
      "overall_risk": 1,
      "long_business_summary": "Hawaiian Electric Industries, Inc., together with its subsidiaries, engages in the electric utility, banking, and renewable/sustainable infrastructure",
      "city": "Honolulu",
      "state": "HI",
      "website": "https://www.hei.com"
  },
  {
      "__typename": "Company",
      "id": "HEI",
      "name": "Heico Corporation",
      "sector": "Industrials",
      "country": "United States",
      "full_time_employees": 5600,
      "compensation_risk": 6,
      "audit_risk": 6,
      "board_risk": 9,
      "overall_risk": 8,
      "long_business_summary": "HEICO Corporation, through its subsidiaries, designs, manufactures, and sells aerospace, defense, and electronic related products and services in the ",
      "city": "Hollywood",
      "state": "FL",
      "website": "https://www.heico.com"
  },
  {
      "__typename": "Company",
      "id": "HL",
      "name": "Hecla Mining Company",
      "sector": "Basic Materials",
      "country": "United States",
      "full_time_employees": 1650,
      "compensation_risk": 1,
      "audit_risk": 8,
      "board_risk": 3,
      "overall_risk": 3,
      "long_business_summary": "Hecla Mining Company, together with its subsidiaries, discovers, acquires, develops, and produces precious and base metal properties in the United Sta",
      "city": "Coeur d'Alene",
      "state": "ID",
      "website": "https://www.hecla-mining.com"
  },
  {
      "__typename": "Company",
      "id": "HLF",
      "name": "Herbalife Nutrition Ltd.",
      "sector": "Consumer Defensive",
      "country": "United States",
      "full_time_employees": 10800,
      "compensation_risk": 5,
      "audit_risk": 3,
      "board_risk": 5,
      "overall_risk": 5,
      "long_business_summary": "Herbalife Nutrition Ltd. offers nutrition solutions in North America, Mexico, South and Central America, Europe, the Middle East, Africa, China, and r",
      "city": "Los Angeles",
      "state": "CA",
      "website": "https://www.herbalife.com"
  },
  {
      "__typename": "Company",
      "id": "HPP",
      "name": "Hudson Pacific Properties, Inc.",
      "sector": "Real Estate",
      "country": "United States",
      "full_time_employees": 560,
      "compensation_risk": 1,
      "audit_risk": 8,
      "board_risk": 7,
      "overall_risk": 5,
      "long_business_summary": "Hudson Pacific is a real estate investment trust with a portfolio of office and studio properties totaling nearly 19 million square feet, including la",
      "city": "Los Angeles",
      "state": "CA",
      "website": "https://www.hudsonpacificproperties.com"
  },
  {
      "__typename": "Company",
      "id": "HPQ",
      "name": "HP Inc.",
      "sector": "Technology",
      "country": "United States",
      "full_time_employees": 51000,
      "compensation_risk": 5,
      "audit_risk": 1,
      "board_risk": 1,
      "overall_risk": 1,
      "long_business_summary": "HP Inc. provides personal computing and other access devices, imaging and printing products, and related technologies, solutions, and services in the ",
      "city": "Palo Alto",
      "state": "CA",
      "website": "https://www.hp.com"
  },
  {
      "__typename": "Company",
      "id": "HSY",
      "name": "Hershey Company (The)",
      "sector": "Consumer Defensive",
      "country": "United States",
      "full_time_employees": 16620,
      "compensation_risk": 4,
      "audit_risk": 1,
      "board_risk": 3,
      "overall_risk": 10,
      "long_business_summary": "The Hershey Company, together with its subsidiaries, engages in the manufacture and sale of confectionery products and pantry items in the United Stat",
      "city": "Hershey",
      "state": "PA",
      "website": "https://www.thehersheycompany.com"
  },
  {
      "__typename": "Company",
      "id": "HTH",
      "name": "Hilltop Holdings Inc.",
      "sector": "Financial Services",
      "country": "United States",
      "full_time_employees": 4650,
      "compensation_risk": 1,
      "audit_risk": 9,
      "board_risk": 9,
      "overall_risk": 6,
      "long_business_summary": "Hilltop Holdings Inc. provides business and consumer banking, and financial products and services. It operates through three segments: Banking, Broker",
      "city": "Dallas",
      "state": "TX",
      "website": "https://www.hilltop-holdings.com"
  },
  {
      "__typename": "Company",
      "id": "HUM",
      "name": "Humana Inc.",
      "sector": "Healthcare",
      "country": "United States",
      "full_time_employees": 95500,
      "compensation_risk": 3,
      "audit_risk": 10,
      "board_risk": 4,
      "overall_risk": 6,
      "long_business_summary": "Humana Inc., together with its subsidiaries, operates as a health and well-being company in the United States. It operates through three segments: Ret",
      "city": "Louisville",
      "state": "KY",
      "website": "https://www.humana.com"
  },
  {
      "__typename": "Company",
      "id": "IBM",
      "name": "International Business Machines Corporation",
      "sector": "Technology",
      "country": "United States",
      "full_time_employees": 282100,
      "compensation_risk": 7,
      "audit_risk": 1,
      "board_risk": 9,
      "overall_risk": 5,
      "long_business_summary": "International Business Machines Corporation provides integrated solutions and services worldwide. The company operates through four business segments:",
      "city": "Armonk",
      "state": "NY",
      "website": "https://www.ibm.com"
  },
  {
      "__typename": "Company",
      "id": "IDA",
      "name": "IDACORP, Inc.",
      "sector": "Utilities",
      "country": "United States",
      "full_time_employees": 1992,
      "compensation_risk": 2,
      "audit_risk": 3,
      "board_risk": 1,
      "overall_risk": 2,
      "long_business_summary": "IDACORP, Inc., together with its subsidiaries, engages in the generation, transmission, distribution, purchase, and sale of electric energy in the Uni",
      "city": "Boise",
      "state": "ID",
      "website": "https://www.idacorpinc.com"
  },
  {
      "__typename": "Company",
      "id": "IP",
      "name": "International Paper Company",
      "sector": "Consumer Cyclical",
      "country": "United States",
      "full_time_employees": 38000,
      "compensation_risk": 4,
      "audit_risk": 5,
      "board_risk": 7,
      "overall_risk": 3,
      "long_business_summary": "International Paper Company operates as a packaging company primarily in United States, the Middle East, Europe, Africa, Pacific Rim, Asia, and rest o",
      "city": "Memphis",
      "state": "TN",
      "website": "https://www.internationalpaper.com"
  },
  {
      "__typename": "Company",
      "id": "IT",
      "name": "Gartner, Inc.",
      "sector": "Technology",
      "country": "United States",
      "full_time_employees": 16600,
      "compensation_risk": 4,
      "audit_risk": 2,
      "board_risk": 2,
      "overall_risk": 1,
      "long_business_summary": "Gartner, Inc. operates as a research and advisory company in the United States, Canada, Europe, the Middle East, Africa, and internationally. It opera",
      "city": "Stamford",
      "state": "CT",
      "website": "https://www.gartner.com"
  },
  {
      "__typename": "Company",
      "id": "ITGR",
      "name": "Integer Holdings Corporation",
      "sector": "Healthcare",
      "country": "United States",
      "full_time_employees": 9000,
      "compensation_risk": 1,
      "audit_risk": 2,
      "board_risk": 1,
      "overall_risk": 1,
      "long_business_summary": "Integer Holdings Corporation operates as a medical device outsource manufacturer in the United States, Puerto Rico, Costa Rica, and internationally. I",
      "city": "Plano",
      "state": "TX",
      "website": "https://www.integer.net"
  },
  {
      "__typename": "Company",
      "id": "ITT",
      "name": "ITT Inc.",
      "sector": "Industrials",
      "country": "United States",
      "full_time_employees": 9900,
      "compensation_risk": 2,
      "audit_risk": 5,
      "board_risk": 1,
      "overall_risk": 1,
      "long_business_summary": "ITT Inc. manufactures and sells engineered critical components and customized technology solutions for the transportation, industrial, and energy mark",
      "city": "White Plains",
      "state": "NY",
      "website": "https://www.itt.com"
  },
  {
      "__typename": "Company",
      "id": "IVZ",
      "name": "Invesco Plc",
      "sector": "Financial Services",
      "country": "United States",
      "full_time_employees": 8506,
      "compensation_risk": 2,
      "audit_risk": 9,
      "board_risk": 4,
      "overall_risk": 3,
      "long_business_summary": "Invesco Ltd. is a publicly owned investment manager. The firm provides its services to retail clients, institutional clients, high-net worth clients, ",
      "city": "Atlanta",
      "state": "GA",
      "website": "https://www.invesco.com"
  },
  {
      "__typename": "Company",
      "id": "JBL",
      "name": "Jabil Inc.",
      "sector": "Technology",
      "country": "United States",
      "full_time_employees": 260000,
      "compensation_risk": 3,
      "audit_risk": 2,
      "board_risk": 3,
      "overall_risk": 9,
      "long_business_summary": "Jabil Inc. provides manufacturing services and solutions worldwide. The company operates in two segments, Electronics Manufacturing Services and Diver",
      "city": "Saint Petersburg",
      "state": "FL",
      "website": "https://www.jabil.com"
  },
  {
      "__typename": "Company",
      "id": "JEF",
      "name": "Jefferies Financial Group Inc.",
      "sector": "Financial Services",
      "country": "United States",
      "full_time_employees": 5619,
      "compensation_risk": 7,
      "audit_risk": 5,
      "board_risk": 2,
      "overall_risk": 2,
      "long_business_summary": "Jefferies Financial Group Inc. engages in the investment banking and capital markets, and asset management businesses in the Americas, Europe, the Mid",
      "city": "New York",
      "state": "NY",
      "website": "https://www.jefferies.com"
  },
  {
      "__typename": "Company",
      "id": "JELD",
      "name": "JELD-WEN Holding, Inc.",
      "sector": "Industrials",
      "country": "United States",
      "full_time_employees": 24700,
      "compensation_risk": 2,
      "audit_risk": 1,
      "board_risk": 1,
      "overall_risk": 1,
      "long_business_summary": "JELD-WEN Holding, Inc. designs, manufactures, and sells doors and windows primarily in North America, Europe, and Australasia. The company offers a li",
      "city": "Charlotte",
      "state": "NC",
      "website": "https://www.jeld-wen.com"
  },
  {
      "__typename": "Company",
      "id": "JILL",
      "name": "J. Jill, Inc.",
      "sector": "Consumer Cyclical",
      "country": "United States",
      "full_time_employees": 1115,
      "compensation_risk": 7,
      "audit_risk": 9,
      "board_risk": 10,
      "overall_risk": 9,
      "long_business_summary": "J.Jill, Inc. operates as an omnichannel retailer for women's apparel under the J.Jill brand in the United States. The company offers knit and woven to",
      "city": "Quincy",
      "state": "MA",
      "website": "https://www.jjill.com"
  },
  {
      "__typename": "Company",
      "id": "JNJ",
      "name": "Johnson & Johnson",
      "sector": "Healthcare",
      "country": "United States",
      "full_time_employees": 141700,
      "compensation_risk": 2,
      "audit_risk": 10,
      "board_risk": 4,
      "overall_risk": 4,
      "long_business_summary": "Johnson & Johnson, together with its subsidiaries, researches and develops, manufactures, and sells various products in the healthcare field worldwide",
      "city": "New Brunswick",
      "state": "NJ",
      "website": "https://www.jnj.com"
  },
  {
      "__typename": "Company",
      "id": "JPM",
      "name": "J P Morgan Chase & Co",
      "sector": "Financial Services",
      "country": "United States",
      "full_time_employees": 278494,
      "compensation_risk": 8,
      "audit_risk": 10,
      "board_risk": 3,
      "overall_risk": 6,
      "long_business_summary": "JPMorgan Chase & Co. operates as a financial services company worldwide. It operates through four segments: Consumer & Community Banking (CCB), Corpor",
      "city": "New York",
      "state": "NY",
      "website": "https://www.jpmorganchase.com"
  },
  {
      "__typename": "Company",
      "id": "JWN",
      "name": "Nordstrom, Inc.",
      "sector": "Consumer Cyclical",
      "country": "United States",
      "full_time_employees": 72000,
      "compensation_risk": 2,
      "audit_risk": 4,
      "board_risk": 6,
      "overall_risk": 2,
      "long_business_summary": "Nordstrom, Inc., a fashion retailer, provides apparels, shoes, beauty, accessories, and home goods for women, men, young adults, and children. It offe",
      "city": "Seattle",
      "state": "WA",
      "website": "https://press.nordstrom.com"
  },
  {
      "__typename": "Company",
      "id": "K",
      "name": "Kellogg Company",
      "sector": "Consumer Defensive",
      "country": "United States",
      "full_time_employees": 31000,
      "compensation_risk": 4,
      "audit_risk": 3,
      "board_risk": 5,
      "overall_risk": 6,
      "long_business_summary": "Kellogg Company, together with its subsidiaries, manufactures and markets snacks and convenience foods. The company operates through four segments: No",
      "city": "Battle Creek",
      "state": "MI",
      "website": "https://www.kelloggcompany.com"
  },
  {
      "__typename": "Company",
      "id": "KO",
      "name": "Coca-Cola Company (The)",
      "sector": "Consumer Defensive",
      "country": "United States",
      "full_time_employees": 79000,
      "compensation_risk": 10,
      "audit_risk": 5,
      "board_risk": 7,
      "overall_risk": 9,
      "long_business_summary": "The Coca-Cola Company, a beverage company, manufactures, markets, and sells various nonalcoholic beverages worldwide. The company provides sparkling s",
      "city": "Atlanta",
      "state": "GA",
      "website": "https://www.coca-colacompany.com"
  },
  {
      "__typename": "Company",
      "id": "KODK",
      "name": "Eastman Kodak Company",
      "sector": "Industrials",
      "country": "United States",
      "full_time_employees": 4200,
      "compensation_risk": 7,
      "audit_risk": 10,
      "board_risk": 9,
      "overall_risk": 7,
      "long_business_summary": "Eastman Kodak Company provides hardware, software, consumables, and services to customers in the commercial print, packaging, publishing, manufacturin",
      "city": "Rochester",
      "state": "NY",
      "website": "https://www.kodak.com"
  },
  {
      "__typename": "Company",
      "id": "LEN",
      "name": "Lennar Corporation",
      "sector": "Consumer Cyclical",
      "country": "United States",
      "full_time_employees": 10753,
      "compensation_risk": 3,
      "audit_risk": 3,
      "board_risk": 9,
      "overall_risk": 9,
      "long_business_summary": "Lennar Corporation, together with its subsidiaries, operates as a homebuilder primarily under the Lennar brand in the United States. It operates throu",
      "city": "Miami",
      "state": "FL",
      "website": "https://www.lennar.com"
  },
  {
      "__typename": "Company",
      "id": "LH",
      "name": "Laboratory Corporation of America Holdings",
      "sector": "Healthcare",
      "country": "United States",
      "full_time_employees": 75000,
      "compensation_risk": 1,
      "audit_risk": 8,
      "board_risk": 7,
      "overall_risk": 1,
      "long_business_summary": "Laboratory Corporation of America Holdings operates as a global life sciences company that provides vital information to help doctors, hospitals, phar",
      "city": "Burlington",
      "state": "NC",
      "website": "https://www.labcorp.com"
  },
  {
      "__typename": "Company",
      "id": "MA",
      "name": "Mastercard Incorporated",
      "sector": "Financial Services",
      "country": "United States",
      "full_time_employees": 24000,
      "compensation_risk": 9,
      "audit_risk": 1,
      "board_risk": 2,
      "overall_risk": 5,
      "long_business_summary": "Mastercard Incorporated, a technology company, provides transaction processing and other payment-related products and services in the United States an",
      "city": "Purchase",
      "state": "NY",
      "website": "https://www.mastercard.com"
  },
  {
      "__typename": "Company",
      "id": "MCD",
      "name": "McDonald&#39;s Corporation",
      "sector": "Consumer Cyclical",
      "country": "United States",
      "full_time_employees": 100000,
      "compensation_risk": 3,
      "audit_risk": 10,
      "board_risk": 4,
      "overall_risk": 7,
      "long_business_summary": "McDonald's Corporation operates and franchises McDonald's restaurants in the United States and internationally. Its restaurants offer hamburgers and c",
      "city": "Chicago",
      "state": "IL",
      "website": "https://corporate.mcdonalds.com"
  },
  {
      "__typename": "Company",
      "id": "MCY",
      "name": "Mercury General Corporation",
      "sector": "Financial Services",
      "country": "United States",
      "full_time_employees": 4300,
      "compensation_risk": 7,
      "audit_risk": 7,
      "board_risk": 5,
      "overall_risk": 5,
      "long_business_summary": "Mercury General Corporation, together with its subsidiaries, engages in writing personal automobile insurance in the United States. The company also w",
      "city": "Los Angeles",
      "state": "CA",
      "website": "https://www.mercuryinsurance.com"
  },
  {
      "__typename": "Company",
      "id": "META",
      "name": "Meta Inc.",
      "sector": "Communication Services",
      "country": "United States",
      "full_time_employees": 83553,
      "compensation_risk": 10,
      "audit_risk": 10,
      "board_risk": 8,
      "overall_risk": 10,
      "long_business_summary": "Meta Platforms, Inc. develops products that enable people to connect and share with friends and family through mobile devices, personal computers, vir",
      "city": "Menlo Park",
      "state": "CA",
      "website": "https://investor.fb.com"
  },
  {
      "__typename": "Company",
      "id": "MG",
      "name": "Mistras Group Inc",
      "sector": "Industrials",
      "country": "United States",
      "full_time_employees": 5400,
      "compensation_risk": 3,
      "audit_risk": 7,
      "board_risk": 5,
      "overall_risk": 4,
      "long_business_summary": "Mistras Group, Inc. provides technology-enabled asset protection solutions worldwide. The company operates through three segments: Services, Internati",
      "city": "Princeton Junction",
      "state": "NJ",
      "website": "https://www.mistrasgroup.com"
  },
  {
      "__typename": "Company",
      "id": "MRVL",
      "name": "Marvel Corp.",
      "sector": "Technology",
      "country": "United States",
      "full_time_employees": 6695,
      "compensation_risk": 5,
      "audit_risk": 5,
      "board_risk": 2,
      "overall_risk": 1,
      "long_business_summary": "Marvell Technology, Inc., together with its subsidiaries, designs, develops, and sells analog, mixed-signal, digital signal processing, and embedded a",
      "city": "Wilmington",
      "state": "DE",
      "website": "https://www.marvell.com"
  },
  {
      "__typename": "Company",
      "id": "NFLX",
      "name": "Netflix Corporation",
      "sector": "Communication Services",
      "country": "United States",
      "full_time_employees": 11300,
      "compensation_risk": 10,
      "audit_risk": 9,
      "board_risk": 10,
      "overall_risk": 10,
      "long_business_summary": "Netflix, Inc. provides entertainment services. It offers TV series, documentaries, feature films, and mobile games across various genres and languages",
      "city": "Los Gatos",
      "state": "CA",
      "website": "https://www.netflix.com"
  },
  {
      "__typename": "Company",
      "id": "NKE",
      "name": "Nike, Inc.",
      "sector": "Consumer Cyclical",
      "country": "United States",
      "full_time_employees": 79100,
      "compensation_risk": 4,
      "audit_risk": 7,
      "board_risk": 10,
      "overall_risk": 9,
      "long_business_summary": "NIKE, Inc., together with its subsidiaries, designs, develops, markets, and sells men's, women's, and kids athletic footwear, apparel, equipment, and ",
      "city": "Beaverton",
      "state": "OR",
      "website": "https://investors.nike.com"
  },
  {
      "__typename": "Company",
      "id": "NSP",
      "name": "Insperity, Inc.",
      "sector": "Industrials",
      "country": "United States",
      "full_time_employees": 3600,
      "compensation_risk": 2,
      "audit_risk": 2,
      "board_risk": 4,
      "overall_risk": 3,
      "long_business_summary": "Insperity, Inc. provides human resources (HR) and business solutions to improve business performance for small and medium-sized businesses. The compan",
      "city": "Kingwood",
      "state": "TX",
      "website": "https://www.insperity.com"
  },
  {
      "__typename": "Company",
      "id": "NVDA",
      "name": "NVIDIA Inc.",
      "sector": "Technology",
      "country": "United States",
      "full_time_employees": 22473,
      "compensation_risk": 2,
      "audit_risk": 10,
      "board_risk": 9,
      "overall_risk": 8,
      "long_business_summary": "NVIDIA Corporation provides graphics, and compute and networking solutions in the United States, Taiwan, China, and internationally. The company's Gra",
      "city": "Santa Clara",
      "state": "CA",
      "website": "https://www.nvidia.com"
  },
  {
      "__typename": "Company",
      "id": "ORCL",
      "name": "Oracle Corporation",
      "sector": "Technology",
      "country": "United States",
      "full_time_employees": 143000,
      "compensation_risk": 10,
      "audit_risk": 8,
      "board_risk": 10,
      "overall_risk": 10,
      "long_business_summary": "Oracle Corporation offers products and services that address enterprise information technology environments worldwide. Its Oracle cloud software as a ",
      "city": "Austin",
      "state": "TX",
      "website": "https://www.oracle.com"
  },
  {
      "__typename": "Company",
      "id": "OXY",
      "name": "Occidental Petroleum Corporation",
      "sector": "Energy",
      "country": "United States",
      "full_time_employees": 11678,
      "compensation_risk": 8,
      "audit_risk": 9,
      "board_risk": 9,
      "overall_risk": 6,
      "long_business_summary": "Occidental Petroleum Corporation, together with its subsidiaries, engages in the acquisition, exploration, and development of oil and gas properties i",
      "city": "Houston",
      "state": "TX",
      "website": "https://www.oxy.com"
  },
  {
      "__typename": "Company",
      "id": "PACK",
      "name": "Ranpak Holdings Corp",
      "sector": "Consumer Cyclical",
      "country": "United States",
      "full_time_employees": 875,
      "compensation_risk": 10,
      "audit_risk": 5,
      "board_risk": 10,
      "overall_risk": 10,
      "long_business_summary": "Ranpak Holdings Corp., together with its subsidiaries, provide product protection solutions for e-commerce and industrial supply chains in North Ameri",
      "city": "Concord Township",
      "state": "OH",
      "website": "https://www.ranpak.com"
  },
  {
      "__typename": "Company",
      "id": "PEP",
      "name": "Pepsi Co.",
      "sector": "Consumer Defensive",
      "country": "United States",
      "full_time_employees": 309000,
      "compensation_risk": 4,
      "audit_risk": 6,
      "board_risk": 7,
      "overall_risk": 3,
      "long_business_summary": "PepsiCo, Inc. manufactures, markets, distributes, and sells various beverages and convenient foods worldwide. The company operates through seven segme",
      "city": "Purchase",
      "state": "NY",
      "website": "https://www.pepsico.com"
  },
  {
      "__typename": "Company",
      "id": "PFE",
      "name": "Pfizer, Inc.",
      "sector": "Healthcare",
      "country": "United States",
      "full_time_employees": 79000,
      "compensation_risk": 1,
      "audit_risk": 10,
      "board_risk": 6,
      "overall_risk": 3,
      "long_business_summary": "Pfizer Inc. discovers, develops, manufactures, markets, distributes, and sells biopharmaceutical products worldwide. It offers medicines and vaccines ",
      "city": "New York",
      "state": "NY",
      "website": "https://www.pfizer.com"
  },
  {
      "__typename": "Company",
      "id": "PGR",
      "name": "Progressive Corporation (The)",
      "sector": "Financial Services",
      "country": "United States",
      "full_time_employees": 49077,
      "compensation_risk": 6,
      "audit_risk": 5,
      "board_risk": 2,
      "overall_risk": 4,
      "long_business_summary": "The Progressive Corporation, an insurance holding company, provides personal and commercial auto, personal residential and commercial property, genera",
      "city": "Mayfield",
      "state": "OH",
      "website": "https://www.progressive.com"
  },
  {
      "__typename": "Company",
      "id": "PYPL",
      "name": "Paypal Inc.",
      "sector": "Financial Services",
      "country": "United States",
      "full_time_employees": 30900,
      "compensation_risk": 7,
      "audit_risk": 2,
      "board_risk": 1,
      "overall_risk": 3,
      "long_business_summary": "PayPal Holdings, Inc. operates a technology platform that enables digital payments on behalf of merchants and consumers worldwide. It provides payment",
      "city": "San Jose",
      "state": "CA",
      "website": "https://www.paypal.com"
  },
  {
      "__typename": "Company",
      "id": "SBUX",
      "name": "Starbucks",
      "sector": "Consumer Cyclical",
      "country": "United States",
      "full_time_employees": 383000,
      "compensation_risk": 1,
      "audit_risk": 1,
      "board_risk": 1,
      "overall_risk": 1,
      "long_business_summary": "Starbucks Corporation, together with its subsidiaries, operates as a roaster, marketer, and retailer of specialty coffee worldwide. The company operat",
      "city": "Seattle",
      "state": "WA",
      "website": "https://www.starbucks.com"
  },
  {
      "__typename": "Company",
      "id": "SYY",
      "name": "Sysco Corporation",
      "sector": "Consumer Defensive",
      "country": "United States",
      "full_time_employees": 71000,
      "compensation_risk": 10,
      "audit_risk": 5,
      "board_risk": 5,
      "overall_risk": 9,
      "long_business_summary": "Sysco Corporation, through its subsidiaries, engages in the marketing and distribution of various food and related products primarily to the foodservi",
      "city": "Houston",
      "state": "TX",
      "website": "https://www.sysco.com"
  },
  {
      "__typename": "Company",
      "id": "TSE",
      "name": "Trinseo S.A.",
      "sector": "Basic Materials",
      "country": "United States",
      "full_time_employees": 3400,
      "compensation_risk": 1,
      "audit_risk": 6,
      "board_risk": 2,
      "overall_risk": 3,
      "long_business_summary": "Trinseo PLC, a materials solutions provider, manufactures and sells plastics and latex binders in the United States, Europe, the Asia-Pacific, and int",
      "city": "Berwyn",
      "state": "PA",
      "website": "https://www.trinseo.com"
  },
  {
      "__typename": "Company",
      "id": "TSLA",
      "name": "Tesla",
      "sector": "Consumer Cyclical",
      "country": "United States",
      "full_time_employees": 99290,
      "compensation_risk": 9,
      "audit_risk": 9,
      "board_risk": 9,
      "overall_risk": 10,
      "long_business_summary": "Tesla, Inc. designs, develops, manufactures, leases, and sells electric vehicles, and energy generation and storage systems in the United States, Chin",
      "city": "Austin",
      "state": "TX",
      "website": "https://www.tesla.com"
  },
  {
      "__typename": "Company",
      "id": "TWI",
      "name": "Titan International, Inc.",
      "sector": "Industrials",
      "country": "United States",
      "full_time_employees": 7500,
      "compensation_risk": 9,
      "audit_risk": 8,
      "board_risk": 8,
      "overall_risk": 7,
      "long_business_summary": "Titan International, Inc., together with its subsidiaries, manufactures and sells wheels, tires, and undercarriage systems and components for off-high",
      "city": "Quincy",
      "state": "IL",
      "website": "https://www.titan-intl.com"
  },
  {
      "__typename": "Company",
      "id": "TWO",
      "name": "Two Harbors Investments Corp",
      "sector": "Real Estate",
      "country": "United States",
      "full_time_employees": 105,
      "compensation_risk": 3,
      "audit_risk": 4,
      "board_risk": 2,
      "overall_risk": 3,
      "long_business_summary": "Two Harbors Investment Corp. operates as a real estate investment trust (REIT) that focuses on investing in, financing, and managing residential mortg",
      "city": "Minnetonka",
      "state": "MN",
      "website": "https://www.twoharborsinvestment.com"
  },
  {
      "__typename": "Company",
      "id": "TWTR",
      "name": "Twitter, Inc.",
      "sector": "Communication Services",
      "country": "United States",
      "full_time_employees": 7500,
      "compensation_risk": 8,
      "audit_risk": 10,
      "board_risk": 4,
      "overall_risk": 9,
      "long_business_summary": "Twitter, Inc. operates as a platform for public self-expression and conversation in real-time. The company's primary product is Twitter, a platform th",
      "city": "San Francisco",
      "state": "CA",
      "website": "https://www.twitter.com"
  },
  {
      "__typename": "Company",
      "id": "TXT",
      "name": "Textron Inc.",
      "sector": "Industrials",
      "country": "United States",
      "full_time_employees": 33000,
      "compensation_risk": 3,
      "audit_risk": 5,
      "board_risk": 7,
      "overall_risk": 5,
      "long_business_summary": "Textron Inc. operates in the aircraft, defense, industrial, and finance businesses. The company's Textron Aviation segment manufactures, sells, and se",
      "city": "Providence",
      "state": "RI",
      "website": "https://www.textron.com"
  },
  {
      "__typename": "Company",
      "id": "TYL",
      "name": "Tyler Technologies, Inc.",
      "sector": "Technology",
      "country": "United States",
      "full_time_employees": 7143,
      "compensation_risk": 5,
      "audit_risk": 10,
      "board_risk": 10,
      "overall_risk": 9,
      "long_business_summary": "Tyler Technologies, Inc. provides integrated information management solutions and services for the public sector. The company operates in three segmen",
      "city": "Plano",
      "state": "TX",
      "website": "https://www.tylertech.com"
  },
  {
      "__typename": "Company",
      "id": "UA",
      "name": "Under Armour, Inc.",
      "sector": "Consumer Cyclical",
      "country": "United States",
      "full_time_employees": 7100,
      "compensation_risk": 10,
      "audit_risk": 6,
      "board_risk": 9,
      "overall_risk": 10,
      "long_business_summary": "Under Armour, Inc., together with its subsidiaries, engages in the developing, marketing, and distributing performance apparel, footwear, and accessor",
      "city": "Baltimore",
      "state": "MD",
      "website": "https://www.underarmour.com"
  },
  {
      "__typename": "Company",
      "id": "UBER",
      "name": "Uber Technologies, Inc.",
      "sector": "Technology",
      "country": "United States",
      "full_time_employees": 32500,
      "compensation_risk": 5,
      "audit_risk": 2,
      "board_risk": 2,
      "overall_risk": 2,
      "long_business_summary": "Uber Technologies, Inc. develops and operates proprietary technology applications in the United States, Canada, Latin America, Europe, the Middle East",
      "city": "San Francisco",
      "state": "CA",
      "website": "https://www.uber.com"
  },
  {
      "__typename": "Company",
      "id": "UI",
      "name": "Ubiquiti Inc.",
      "sector": "Technology",
      "country": "United States",
      "full_time_employees": 1377,
      "compensation_risk": 8,
      "audit_risk": 10,
      "board_risk": 9,
      "overall_risk": 9,
      "long_business_summary": "Ubiquiti Inc. develops networking technology for service providers, enterprises, and consumers. The company develops technology platforms for high-cap",
      "city": "New York",
      "state": "NY",
      "website": "https://www.ui.com"
  },
  {
      "__typename": "Company",
      "id": "UPS",
      "name": "United Parcel Service, Inc.",
      "sector": "Industrials",
      "country": "United States",
      "full_time_employees": 534000,
      "compensation_risk": 7,
      "audit_risk": 9,
      "board_risk": 2,
      "overall_risk": 9,
      "long_business_summary": "United Parcel Service, Inc. provides letter and package delivery, transportation, logistics, and related services. It operates through two segments, U",
      "city": "Atlanta",
      "state": "GA",
      "website": "https://www.ups.com"
  },
  {
      "__typename": "Company",
      "id": "USB",
      "name": "U.S. Bancorp",
      "sector": "Financial Services",
      "country": "United States",
      "full_time_employees": 70000,
      "compensation_risk": 5,
      "audit_risk": 9,
      "board_risk": 3,
      "overall_risk": 5,
      "long_business_summary": "U.S. Bancorp, a financial services holding company, provides various financial services to individuals, businesses, institutional organizations, gover",
      "city": "Minneapolis",
      "state": "MN",
      "website": "https://www.usbank.com"
  },
  {
      "__typename": "Company",
      "id": "V",
      "name": "Visa Inc.",
      "sector": "Financial Services",
      "country": "United States",
      "full_time_employees": 21500,
      "compensation_risk": 4,
      "audit_risk": 10,
      "board_risk": 5,
      "overall_risk": 4,
      "long_business_summary": "Visa Inc. operates as a payments technology company worldwide. The company facilitates digital payments among consumers, merchants, financial institut",
      "city": "San Francisco",
      "state": "CA",
      "website": "https://usa.visa.com"
  },
  {
      "__typename": "Company",
      "id": "VAPO",
      "name": "Vapotherm, Inc.",
      "sector": "Healthcare",
      "country": "United States",
      "full_time_employees": 510,
      "compensation_risk": 7,
      "audit_risk": 6,
      "board_risk": 7,
      "overall_risk": 7,
      "long_business_summary": "Vapotherm, Inc., a medical technology company, focuses on the development and commercialization of proprietary high velocity therapy products used to ",
      "city": "Exeter",
      "state": "NH",
      "website": "https://www.vapotherm.com"
  },
  {
      "__typename": "Company",
      "id": "VHI",
      "name": "Valhi, Inc.",
      "sector": "Basic Materials",
      "country": "United States",
      "full_time_employees": 2847,
      "compensation_risk": 6,
      "audit_risk": 3,
      "board_risk": 9,
      "overall_risk": 7,
      "long_business_summary": "Valhi, Inc. engages in the chemicals, component products, and real estate management and development businesses in the Asia Pacific, Europe, North Ame",
      "city": "Dallas",
      "state": "TX",
      "website": "https://www.valhi.net"
  },
  {
      "__typename": "Company",
      "id": "VICI",
      "name": "VICI Properties Inc.",
      "sector": "Real Estate",
      "country": "United States",
      "full_time_employees": 105,
      "compensation_risk": 1,
      "audit_risk": 3,
      "board_risk": 1,
      "overall_risk": 2,
      "long_business_summary": "VICI Properties is an experiential real estate investment trust that owns one of the largest portfolios of market-leading gaming, hospitality and ente",
      "city": "New York",
      "state": "NY",
      "website": "https://www.viciproperties.com"
  },
  {
      "__typename": "Company",
      "id": "VNO",
      "name": "Vornado Realty Trust",
      "sector": "Real Estate",
      "country": "United States",
      "full_time_employees": 3224,
      "compensation_risk": 9,
      "audit_risk": 9,
      "board_risk": 8,
      "overall_risk": 10,
      "long_business_summary": "Vornado's portfolio is concentrated in the nation's key market  New York City  along with the premier asset in both Chicago and San Francisco. Vorna",
      "city": "New York",
      "state": "NY",
      "website": "https://www.vno.com"
  },
  {
      "__typename": "Company",
      "id": "VOYA",
      "name": "Voya Financial, Inc.",
      "sector": "Financial Services",
      "country": "United States",
      "full_time_employees": 6000,
      "compensation_risk": 2,
      "audit_risk": 3,
      "board_risk": 1,
      "overall_risk": 2,
      "long_business_summary": "Voya Financial, Inc. operates as a retirement, investment, and employee benefits company in the United States. The company's Wealth Solutions segment ",
      "city": "New York",
      "state": "NY",
      "website": "https://www.voya.com"
  },
  {
      "__typename": "Company",
      "id": "VVV",
      "name": "Valvoline Inc.",
      "sector": "Energy",
      "country": "United States",
      "full_time_employees": 9800,
      "compensation_risk": 2,
      "audit_risk": 4,
      "board_risk": 1,
      "overall_risk": 1,
      "long_business_summary": "Valvoline Inc. manufactures, markets, and supplies, engine and automotive maintenance products and services. It operates through two segments, Retail ",
      "city": "Lexington",
      "state": "KY",
      "website": "https://www.valvoline.com"
  },
  {
      "__typename": "Company",
      "id": "VZ",
      "name": "Verizon Communications Inc.",
      "sector": "Communication Services",
      "country": "United States",
      "full_time_employees": 119400,
      "compensation_risk": 2,
      "audit_risk": 4,
      "board_risk": 6,
      "overall_risk": 2,
      "long_business_summary": "Verizon Communications Inc., through its subsidiaries, offers communications, technology, information, and entertainment products and services to cons",
      "city": "New York",
      "state": "NY",
      "website": "https://www.verizon.com"
  },
  {
      "__typename": "Company",
      "id": "WAT",
      "name": "Waters Corporation",
      "sector": "Healthcare",
      "country": "United States",
      "full_time_employees": 7800,
      "compensation_risk": 7,
      "audit_risk": 9,
      "board_risk": 2,
      "overall_risk": 6,
      "long_business_summary": "Waters Corporation, a specialty measurement company, provides analytical workflow solutions in Asia, the Americas, and Europe. It operates through two",
      "city": "Milford",
      "state": "MA",
      "website": "https://www.waters.com"
  },
  {
      "__typename": "Company",
      "id": "WBD",
      "name": "Warner Bros.",
      "sector": "Communication Services",
      "country": "United States",
      "full_time_employees": 11000,
      "compensation_risk": 10,
      "audit_risk": 10,
      "board_risk": 10,
      "overall_risk": 10,
      "long_business_summary": "Warner Bros. Discovery, Inc., a media company, provides content across various distribution platforms in approximately 50 languages worldwide. It also",
      "city": "New York",
      "state": "NY",
      "website": "https://corporate.discovery.com"
  },
  {
      "__typename": "Company",
      "id": "WHR",
      "name": "Whirlpool Corporation",
      "sector": "Consumer Cyclical",
      "country": "United States",
      "full_time_employees": 69000,
      "compensation_risk": 8,
      "audit_risk": 8,
      "board_risk": 8,
      "overall_risk": 7,
      "long_business_summary": "Whirlpool Corporation manufactures and markets home appliances and related products. It operates through four segments: North America; Europe, Middle ",
      "city": "Benton Harbor",
      "state": "MI",
      "website": "https://www.whirlpoolcorp.com"
  },
  {
      "__typename": "Company",
      "id": "WMT",
      "name": "Walmart Inc.",
      "sector": "Consumer Defensive",
      "country": "United States",
      "full_time_employees": 2300000,
      "compensation_risk": 8,
      "audit_risk": 7,
      "board_risk": 7,
      "overall_risk": 4,
      "long_business_summary": "Walmart Inc. engages in the operation of retail, wholesale, and other units worldwide. The company operates through three segments: Walmart U.S., Walm",
      "city": "Bentonville",
      "state": "AR",
      "website": "https://www.stock.walmart.com"
  },
  {
      "__typename": "Company",
      "id": "WOW",
      "name": "WideOpenWest, Inc.",
      "sector": "Communication Services",
      "country": "United States",
      "full_time_employees": 1500,
      "compensation_risk": 4,
      "audit_risk": 8,
      "board_risk": 6,
      "overall_risk": 6,
      "long_business_summary": "WideOpenWest, Inc. provides high speed data, cable television, and digital telephony services to residential and business services customers in the Un",
      "city": "Englewood",
      "state": "CO",
      "website": "https://www.wowway.com"
  },
  {
      "__typename": "Company",
      "id": "WPC",
      "name": "W.P. Carey Inc.",
      "sector": "Real Estate",
      "country": "United States",
      "full_time_employees": 183,
      "compensation_risk": 1,
      "audit_risk": 1,
      "board_risk": 1,
      "overall_risk": 1,
      "long_business_summary": "W. P. Carey ranks among the largest net lease REITs with an enterprise value of approximately $18 billion and a diversified portfolio of operationally",
      "city": "New York",
      "state": "NY",
      "website": "https://www.wpcarey.com"
  },
  {
      "__typename": "Company",
      "id": "WWE",
      "name": "World Wrestling Entertainment, Inc.",
      "sector": "Communication Services",
      "country": "United States",
      "full_time_employees": 870,
      "compensation_risk": 4,
      "audit_risk": 10,
      "board_risk": 6,
      "overall_risk": 8,
      "long_business_summary": "World Wrestling Entertainment, Inc., an integrated media and entertainment company, engages in the sports entertainment business in North America, Eur",
      "city": "Stamford",
      "state": "CT",
      "website": "https://corporate.wwe.com"
  },
  {
      "__typename": "Company",
      "id": "WWW",
      "name": "Wolverine World Wide, Inc.",
      "sector": "Consumer Cyclical",
      "country": "United States",
      "full_time_employees": 4400,
      "compensation_risk": 2,
      "audit_risk": 3,
      "board_risk": 3,
      "overall_risk": 2,
      "long_business_summary": "Wolverine World Wide, Inc. designs, manufactures, sources, markets, licenses, and distributes footwear, apparel, and accessories in the United States,",
      "city": "Rockford",
      "state": "MI",
      "website": "https://www.wolverineworldwide.com"
  },
  {
      "__typename": "Company",
      "id": "X",
      "name": "United States Steel Corporation",
      "sector": "Basic Materials",
      "country": "United States",
      "full_time_employees": 24540,
      "compensation_risk": 3,
      "audit_risk": 3,
      "board_risk": 2,
      "overall_risk": 2,
      "long_business_summary": "United States Steel Corporation produces and sells flat-rolled and tubular steel products primarily in North America and Europe. It operates through f",
      "city": "Pittsburgh",
      "state": "PA",
      "website": "https://www.ussteel.com"
  },
  {
      "__typename": "Company",
      "id": "XOM",
      "name": "Exxon Mobil Corporation",
      "sector": "Energy",
      "country": "United States",
      "full_time_employees": 63000,
      "compensation_risk": 9,
      "audit_risk": 9,
      "board_risk": 5,
      "overall_risk": 6,
      "long_business_summary": "Exxon Mobil Corporation explores for and produces crude oil and natural gas in the United States and internationally. It operates through Upstream, Do",
      "city": "Irving",
      "state": "TX",
      "website": "https://corporate.exxonmobil.com"
  },
  {
      "__typename": "Company",
      "id": "YELP",
      "name": "Yelp Inc.",
      "sector": "Communication Services",
      "country": "United States",
      "full_time_employees": 4400,
      "compensation_risk": 5,
      "audit_risk": 7,
      "board_risk": 2,
      "overall_risk": 4,
      "long_business_summary": "Yelp Inc. operates a platform that connects consumers with local businesses in the United States and internationally. The company's platform covers va",
      "city": "San Francisco",
      "state": "CA",
      "website": "https://www.yelp.com"
  },
  {
      "__typename": "Company",
      "id": "ZTS",
      "name": "Zoetis Inc.",
      "sector": "Healthcare",
      "country": "United States",
      "full_time_employees": 12100,
      "compensation_risk": 3,
      "audit_risk": 5,
      "board_risk": 1,
      "overall_risk": 3,
      "long_business_summary": "Zoetis Inc. discovers, develops, manufactures, and commercializes animal health medicines, vaccines, and diagnostic products in the United States and ",
      "city": "Parsippany",
      "state": "NJ",
      "website": "https://www.zoetis.com"
  }
]

export default CompaniesMock
